[preferred]
# Fallback default untuk GTK apps
default=gtk

# Konfigurasi khusus untuk Hyprland
hyprland:Hyprland
org.freedesktop.impl.portal.Screenshot=hyprland
org.freedesktop.impl.portal.ScreenCast=hyprland
org.freedesktop.impl.portal.Inhibit=hyprland
org.freedesktop.impl.portal.FileChooser=gtk

# Konfigurasi khusus untuk GNOME
gnome:GNOME
default=gnome
